version: '3'

services:
  postgres:
    image: postgres
    environment: 
      - POSTGRES_DB=my-store
      - POSTGRES_USER=dany
      - POSTGRES_PASSWORD=54321
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
